#pragma once

namespace rczEngine
{
	enum eCOMPONENT_ID
	{
		CMP_NONE = 0,
		CMP_CAMERA,
		CMP_TRANSFORM,
		CMP_MODEL_RENDERER,
		CMP_SKINNED_MODEL_RENDERER,
		CMP_LIGHT,
		CMP_MOVE,
		CMP_TERRAIN_RENDERER,
		CMP_CAMERA_GHOST,
		CMP_CAMERA_WALK,
		CMP_SPACE_MANAGER,
		CMP_SPACE_TRAVEL,
		CMP_BONE,
		CMP_MAX
	};
};